# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	git
	zsh-syntax-highlighting
	docker
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# PATH Environment
# Golang
export GOROOT="/usr/local/go"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin:$GOROOT/bin"
# JAVA 8
export JAVA_HOME=/opt/jdk
export JRE_HOME=/opt/jdk/jre
export M2_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}
# python
export PY_VIRTUAL_ENV="/home/shuvojit/.local/bin"
export PATH=$PATH:$PY_VIRTUAL_ENV
# sls environments
export SLS_DEBUG=*
# jetbrains agent
alias JETBRAINS_AGENT="echo '-javaagent:/home/shuvojit/opt/jetbrains-agent/jetbrains-agent.jar'"
# aliasing
# file
alias edit-zsh="subl ~/.zshrc"
alias edit-profile="subl ~/.zshrc"
alias source-zsh="source ~/.zshrc"
alias source-profile="source ~/.zshrc"
alias edit-sudoers="sudo subl /etc/sudoers"
alias edit-hosts="sudo subl /etc/hosts"
alias edit-git-exclude="subl .git/info/exclude"
# Directory
alias cd-ibfd-kaz="$HOME/Desktop/IBFD-KAZ"
alias cd-ibfd-kaz-client="$HOME/Desktop/IBFD-KAZ/client"
alias cd-ibfd-kaz-server="$HOME/Desktop/IBFD-KAZ/server"
alias cd-ibfd-kaz-driver="$HOME/Desktop/IBFD-KAZ/driver"
alias cd-ibfd-kaz-driver-cvs="$HOME/Desktop/IBFD-KAZ/driver-cvs"
alias cd-ibfd-kaz-doc="$HOME/Desktop/IBFD-KAZ/doc"
alias cd-ibfd-kaz-db-local="$HOME/Desktop/IBFD-KAZ/docker-db"
alias cd-home="cd $HOME"
alias cd-learning="cd $HOME/Desktop/Learning"
alias ibfd-test-user="cat $HOME/Desktop/IBFD-KAZ/test-users.json"
alias azure-test-user="cat $HOME/Desktop/IBFD-KAZ/azure-ad-test-users.json"
# scripts
alias update="sudo apt update"
alias upgrade="sudo apt upgrade"
# angular
alias run-ng-build="ng build"
alias run-ng-build-prod="ng build --prod"
alias run-ng-lint="ng lint"
alias run-ng-test="ng test"
alias run-ng-test-headless="ng test --watch=false --browsers=ChromeHeadless"
alias run-ng-proxy="ng serve --host=shuvojit.ibfd.org --port=4200 --proxy-config proxy-conf.json"
alias run-ng-proxy-export="ng serve --host=0.0.0.0 --port=4200 --proxy-config proxy-conf.json"
alias run-ng-lint-prod-test="ng lint && ng build --prod && ng test"
alias run-packagr="npm run packagr"
alias run-trp="ng serve --host=shuvojit.ibfd.org --port=8080 --proxy-config proxy-conf.json"
alias run-ng="ng serve --host=shuvojit.ibfd.org --port=4200"
# golang
alias run-go-app="chmod +x run.sh && ./run.sh local"
alias run-go-app-dev="chmod +x run.sh && ./run.sh dev"
# git
alias gbr="git branch"
alias gps="git push"
alias gpsm="git push origin master"
alias gpl="git pull"
alias gplm="git pull origin master"
alias gplmain="git pull origin main"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gst="git status"
alias gdf="git diff"
alias gad="git add"
alias gch="git checkout"
alias gchm="git checkout master"
alias gchmain="git checkout main"
alias gcb="git checkout -b"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias git-ibfd-config="git config user.email shuvojit.saha@kaz.com.bd && git config user.name 'Shuvojit Saha'"
alias git-self-config="git config user.email shuvojitsahashuvo@gmail.com && git config user.name 'ParthoShuvo'"
alias git-global-config="git config --global user.email shuvojit.saha@kaz.com.bd && git config --global user.name 'Shuvojit Saha'"
alias sping="ping -c 5 www.stackoverflow.com"
alias gping="ping -c 5 www.google.com"
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/shuvojit/.sdkman"
[[ -s "/home/shuvojit/.sdkman/bin/sdkman-init.sh" ]] && source "/home/shuvojit/.sdkman/bin/sdkman-init.sh"
# intellji
alias datagrip="sudo /usr/local/bin/datagrip &"
# chrome
alias chrome-cors='google-chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security &'

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/shuvojit/Desktop/Learning/serverless/angularSeo/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/shuvojit/Desktop/Learning/serverless/angularSeo/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/shuvojit/Desktop/Learning/serverless/angularSeo/node_modules/tabtab/.completions/sls.zsh ]] && . /home/shuvojit/Desktop/Learning/serverless/angularSeo/node_modules/tabtab/.completions/sls.zsh